Updated files

diff --git a/bin/genapi b/bin/genapi
--- a/bin/genapi
+++ b/bin/genapi
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-# help message
-
 print_help() {
 echo "Usage: GenMat [options] [--name <analysis name>]
 
@@ -33,6 +31,12 @@ echo "Usage: GenMat [options] [--name <analysis name>]
         -v, --version   Print the tool version.
         -h, --help      Print this message.
         " >&2 ;
+}
+
+not_found(){
+	echo "ERROR: $1 is not installed or not included in the path." >&2;
+        exit 1
+
 }
 
 
@@ -100,67 +104,64 @@ Contact: migle.gabrielaite@gmail.com"
 	exit 2
 fi
 
+
 # checking if the required programs are installed
 if ! [ -x "$(command -v blastn)" ]; then
- 	echo 'ERROR: blast is not installed or not included in the path.' >&2
- 	exit 1
+	not_found blast
 fi
 
 if ! [ -x "$(command -v cd-hit-est)" ]; then
- 	echo 'ERROR: CD-HIT is not installed or not included in the path.' >&2
- 	exit 1
+	not_found CD-HIT
 fi
 
 if ! [ -x "$(command -v bedtools)" ]; then
- 	echo 'ERROR: bedtools is not installed or not included in the path.' >&2
- 	exit 1
+	not_found bedtools
 fi
 
+
 # Checking if there are any GFF files present for analysis
+
 if [ ! `ls -1 *gff 2>/dev/null | wc -l ` -gt 0 ]
 then
 	echo 'ERROR: GFF files are not present in the analysis directory.' >&2
 	exit 1
 fi
 
+
+
+
+
+
+# Analysis script start
+
+
 # printing all the settings to a settings file
 
-echo "Analysis name: $NAME
-Number of threads:$THREADS
-Alignment coverage threshold for CD-HIT-EST: $ALIGNMENT_COVERAGE
-Identity threshold for CD-HIT-EST: $IDENTITY
-First minimum threshold for gene coverage: $geneCov1
-Second minimum threshold for gene coverage: $geneCov2
-First minimum threshold for gene identity: $geneIden1
-Second minimum threshold for gene identity: $geneIden2
-Minimum gene length used for analysis: $geneLen" > ${NAME}_settings
+sh settings.sh $NAME $THREADS $ALIGNMENT_COVERAGE $IDENTITY $geneCov1 $geneCov2 $geneIden1 $geneIden2 $geneLen
 
 
 mkdir -p output_results/
 
+split_gff(){
+	file=$1
+	file_start=`echo ${file} | sed 's/\.gff//'`
+        awk '/##FASTA/,0{if (!/##FASTA/)print}' < $file > ${file_start}.fasta
+
+        sed '/##FASTA/Q' < $file | grep -v "##" > ${file_start}_temp.tsv
+        cat ${file_start}_temp.tsv | awk -F'\t' '{print $1, $4, $5}' | tr " " "\t" > tmp00
+        cat ${file_start}_temp.tsv | awk -F'ID=' '{print $2}' | sed -e 's/;.*//' > tmp01
+
+        paste tmp00 tmp01 -d '\t'  > ${file_start}.bed
+
+        bedtools getfasta -fi ${file_start}.fasta -bed ${file_start}.bed -fo ${file_start}.ffn -name
+        rm -f tmp00 tmp01 ${file_start}.bed ${file_start}_temp.tsv
+}
+
+
 # extracting ffn and scaffolds.fasta files from gff files
 for file in ./*.gff
 do
-	file_start=`echo ${file} | sed 's/\.gff//'`
-	awk '/##FASTA/,0{if (!/##FASTA/)print}' < $file > ${file_start}.fasta
-	
-	sed '/##FASTA/Q' < $file | grep -v "##" > ${file_start}_temp.tsv
-	cat ${file_start}_temp.tsv | awk -F'\t' '{print $1, $4, $5}' | tr " " "\t" > tmp00	
-	cat ${file_start}_temp.tsv | awk -F'ID=' '{print $2}' | sed -e 's/;.*//' > tmp01
-	#cat ${file_start}_temp.tsv | awk -F'product=' '{print $2}' | sed -e 's/;.*//' | tr " " "_" > tmp02
-
-	#paste tmp01 tmp02 -d _ > tmp03
-	#paste tmp00 tmp03 -d '\t'  > ${file_start}.bed
-
-
-	paste tmp00 tmp01 -d '\t'  > ${file_start}.bed
-	
-
-	
-	bedtools getfasta -fi ${file_start}.fasta -bed ${file_start}.bed -fo ${file_start}.ffn -name	
-	#rm -f tmp00 tmp01 tmp02 tmp03 ${file_start}.bed ${file_start}_temp.tsv
-	rm -f tmp00 tmp01 ${file_start}.bed ${file_start}_temp.tsv
-
+	split_gff $file $
 done
 
 # creating a file of all the genes and clustering it with cd-hit-est
@@ -184,16 +185,13 @@ rm -f output_results/all_genes_${NAME}
 # blast each sequence to the clustered database
 
 echo -en "-----FINDING THE BEST ALIGNMENT FOR EACH GENE SEQUENCE-----\n"
-gene_db_alignment_against_seq.sh  ${NAME} ${geneCov1} ${geneCov2} ${geneIden1} ${geneIden2} ${THREADS}
+sh gene_db_alignment_against_seq.sh  ${NAME} ${geneCov1} ${geneCov2} ${geneIden1} ${geneIden2} ${THREADS}
 
 echo -en "-----CREATING GENE PRESENCE/ABSENCE MATRIX-----\n"
-convert_gene_alignment_to_binary.sh  ${NAME} ${geneCov1} ${geneCov2} ${geneIden1} ${geneIden2} ${geneLen}
+sh convert_gene_alignment_to_binary.sh  ${NAME} ${geneCov1} ${geneCov2} ${geneIden1} ${geneIden2} ${geneLen}
 
 echo -en "-----THE ANALYSIS IS DONE-----\n"
 
-rm -f *.fasta 
-rm -f *.fasta.fai
-rm -f *.ffn
 
 
 # generate the phylogenetic tree based on the gene presence-absence matrix
@@ -201,12 +199,18 @@ rm -f *.ffn
 if $PHYL_TREE
 then
 	if ! [ -x "$(command -v raxmlHPC)" ]; then
-        	echo 'ERROR: RAxML is not installed or not included in the path.' >&2
-        	exit 1
+		not_found RAxML
 	fi
-
-	phylogenetic_analysis.sh ${NAME}
+	echo -en "-----GENERATING THE PHYLOGENETIC TREE-----\n"
+	sh phylogenetic_analysis.sh ${NAME}
 fi
+
+
+
+# remove temporary files
+
+sh remove_temp.sh ${NAME}
+
 
 
 # generate the gene presence-absence matrix visualizations
@@ -214,16 +218,15 @@ fi
 if $VISUALIZE
 then
 
-	if ! [ -x "$(command -v blastn)" ]; then
-        	echo 'ERROR: blast is not installed or not included in the path.' >&2
-        	exit 1
+	if ! [ -x "$(command -v Rscript)" ]; then
+		not_found Rscript
 	fi
-
+	
+	echo -en "-----PLOTTING GENE PRESENCE-ABSENCE HEATMAPS-----\n"
 	# generate the gene presence-absence matrix visualization for only gained/lost genes
+	heatmaps=`command -v generate_heatmaps.R`
+	Rscript $heatmaps ${NAME}
 
-	Rscript generate_heatmap_missing.R ${NAME}
-
-	# generate the gene presence-absence matrix visualization for all genes
-
-	Rscript generate_heatmap_all.R ${NAME}
 fi
+
+
